# Generated by Django 3.0.2 on 2023-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
