# Generated by Django 3.0.2 on 2023-06-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Images'),
            preserve_default=False,
        ),
    ]
