# Generated by Django 3.0.2 on 2023-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploader',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
